export const LOGO = "/images/logo.png";
export const TWITTER = "/icons/twitter.svg";
export const DISCORD = "/icons/discord.svg";
export const TICTOK = "/icons/tictok.svg";
export const MEDIUM = "/icons/medium.svg";
export const LINKEDIN = "/icons/linkedin.svg";
export const OPEN_SEA = "/icons/openSea.svg";
export const INSTAGRAM = "/icons/instagram.svg";
export const GREATER_THAN_SIGN = "/icons/greaterThanSign.svg";
export const LADY_IMAGE = "/images/girlImages.png";
export const GIRL_INTO_PIECE = "/images/girlIntoPiece.png";
export const MUSCLE = "/icons/muscle.svg";
export const ACCOUNTIBILITY = "/icons/accountibility.svg";
export const ROCKET = "/icons/rocket.svg";
export const NEXT_ARROW = "/icons/arrow.svg";
export const ASK_ME = "/icons/askMe.svg";
export const MISSION_LOGO = "/images/missionLogo.png";
export const JOIN_TEAM_GIRL_ONE = "/images/joinTeamGirl1.png";
export const JOIN_TEAM_GIRL_TWO = "/images/joinTeamGirl2.png";
export const JOIN_TEAM_GIRL_THREE = "/images/joinTeamGirl3.png";
export const JOIN_TEAM_GIRL_FOUR = "/images/joinTeamGirl4.png";
export const JOIN_TEAM_GIRL_FIVE = "/images/joinTeamGirl5.png";
export const JOIN_TEAM_GIRL_SIX = "/images/joinTeamGirl6.png";
export const CAROSUEL_GIRL_ONE = "/images/carosuelGirlOne.png";
export const CAROSUEL_GIRL_TWO = "/images/carosuelGirlTwo.png";
export const GAILA = "/images/Gaila.png";
export const CAROSUEL_GIRL_THREE = "/images/carosuelGirlThree.png";
export const MAIL = "/icons/mail.svg";
export const PHONE = "/icons/phone.svg";
export const depth = "/images/depth.png";
export const darkDepth = "/icons/darkDepth.svg";
export const lightDepth = "/icons/lightDepth.svg";
export const LINE_ONE = "/images/lineOne.svg";
export const LINE_TWO = "/images/lineTwo.svg";
export const DRAW_LINES = "/icons/lines.svg";
export const SPIRAL_LINES = "/icons/spiral.svg";

// export const Gigi = "/images/Gigi.png"
// export const Mel = "/images/Mel.PNG"
// export const Rachel = "/images/Rachel.PNG"
// export const Ringaile = "/images/Ringaile.png"

export const Rachel = "/images/Rachel.PNG";
export const Mel = "/images/Mel.PNG";
export const Ashley = "/images/AshleyOld.png";
export const Lily = "/images/Lily.PNG";
export const Bonnie = "/images/Bonnie.png";
export const Emily = "/images/Emily.png";
export const Gaila = "/images/Gigi.png";
